const wordsGroup = [
  ['accept', 'aceptar'],
  ['ask', 'preguntar'],
  ['be', 'ser / estar'],
  ['begin', 'empezar'],
  ['become', 'hacerse'],
  ['believe', 'creer'],
  ['break', 'romper'],
  ['bring', 'traer'],
  ['build', 'construir'],
  ['buy', 'comprar'],
  ['call', 'llamar'],
  ['can', '	poder'],
  ['cancel', 'cancelar'],
  ['carry', 'llevar'],
  ['catch', 'atrapar / agarrar'],
  ['change', 'cambiar'],
  ['choose', 'escoger'],
  ['clean', 'limpiar'],
  ['close', 'cerrar'],
  ['come', 'venir'],
  ['cut', 'cortar'],
  ['dance', 'bailar'],
  ['decide', 'decidir'],
  ['do', 'hacer'],
  ['draw', 'dibujar'],
  ['drink', 'beber'],
  ['drive', 'conducir'],
  ['eat', 'comer'],
  ['explain', 'explicar'],
  ['fall', 'caerse'],
  ['feel', 'sentir'],
  ['fill', 'llenar'],
  ['find', 'encontrar'],
  ['finish', 'terminar'],
  ['fit', 'caber'],
  ['fix', 'reparar'],
  ['fly', 'volar'],
  ['forget', 'olvidar'],
  ['get', 'conseguir'],
  ['give', 'dar'],
  ['go', 'ir'],
  ['happen', 'pasar'],
  ['have', 'tener'],
  ['hear', 'oír'],
  ['hit', 'pegar / golpear'],
  ['hurt', 'dañar / herir'],
  ['keep', 'mantener'],
  ['know', 'saber / conocer'],
  ['let', 'dejar'],
  ['learn', 'aprender'],
  ['leave', 'salir / marcharse'],
  ['listen', 'escuchar'],
  ['live', 'vivir'],
  ['look', 'mirar'],
  ['lose', 'perder'],
  ['make', 'hacer'],
  ['meet', 'conocer'],
  ['move', 'mover'],
  ['need', 'necesitar'],
  ['open', 'abrir'],
  ['pay', 'pagar'],
  ['play', 'jugar'],
  ['put', 'poner'],
  ['read', 'leer'],
  ['reply', 'responder'],
  ['run', 'correr'],
  ['say', 'decir'],
  ['see', 'ver'],
  ['seem', 'parecer'],
  ['sell', 'vender'],
  ['send', 'enviar'],
  ['set', 'poner'],
  ['show', 'mostrar'],
  ['sign', 'firmar'],
  ['sit', 'sentarse'],
  ['sleep', 'dormir'],
  ['speak', 'hablar'],
  ['spell', 'deletrear'],
  ['spend', 'gastar'],
  ['stand', 'ponerse de pie'],
  ['start', 'comenzar'],
  ['stop', 'parar'],
  ['study', 'estudiar'],
  ['take', 'tomar'],
  ['talk', 'hablar'],
  ['teach', 'enseñar'],
  ['tell', 'decir'],
  ['think', 'pensar'],
  ['try', 'intentar'],
  ['turn', 'doblar'],
  ['understand', 'entender'],
  ['use', 'utilizar / usar'],
  ['wait', 'esperar'],
  ['walk', 'caminar'],
  ['want', 'querer / desear'],
  ['watch', 'mirar'],
  ['win', 'ganar'],
  ['work', 'trabajar'],
  ['worry', 'preocuparse'],
  ['write', 'escribir']
];

const getListWordsPair = () => {
  return wordsGroup;
}

export {
  getListWordsPair,
}
